services:

  synset-postgres:
    image: postgres:16-alpine
    container_name: synset-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: tecto
    volumes:
      - synset_postgres_data:/var/lib/postgresql/data
    networks: [dokploy-network]

  tecto:
    image: ghcr.io/dev-fcastro/tecto:latest
    pull_policy: always
    volumes:
      - tecto_pdfs:/app/pdfs
      - tecto_assets:/app/assets
    restart: unless-stopped
    depends_on:
      - synset-postgres
    environment:
      DATABASE_URL: ******synset-postgres:5432/tecto
    networks: [dokploy-network]
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - "traefik.http.routers.tecto.rule=Host(`tecto.synsetsolutions.com`)"
      - traefik.http.routers.tecto.entrypoints=websecure
      - traefik.http.routers.tecto.tls.certresolver=le
      - traefik.http.services.tecto.loadbalancer.server.port=8080


networks:
  dokploy-network:
    external: true

volumes:
  synset_postgres_data:
  tecto_pdfs:
  tecto_assets:
